services:
  api:
    build: ./shopper-backend
    ports:
      - 3000:3000
    environment:
      - MONGODB_CONNECTION_URI=mongodb://admin:admin@mongo:27017/
      - GEMINI_GENERATIVE_MODEL_VERSION=gemini-1.5-pro
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo

  webapp:
    build:
      context: ./shopper-frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
    ports:
      - 80:80
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
